name: Build and publish
run-name: ${{ github.actor }} is running this Action

on: 
  push:
    branches: ['release']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: docker-ubuntu-nodejs

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from versions.txt
        id: read-version
        run: |
          latest_version=$(head -1 VERSION.txt)
          echo "Build the latest version: $latest_version"
          echo "::set-output name=latest_version::$latest_version"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ steps.read-version.outputs.latest_version }}
          push: true
          tags: ghcr.io/ci-db/docker-ubuntu-nodejs:latest,ghcr.io/ci-db/docker-ubuntu-nodejs:${{ steps.read-version.outputs.latest_version }}
      
      
      